name: landscape_analysis
description: A cli for analyzing pubspec files and generating visual dependency graphs using Graphviz.
version: 0.0.1
repository: https://github.com/Jannik-dev/landscape_analysis
issue_tracker: https://github.com/Jannik-dev/landscape_analysis/issues

environment:
  sdk: ^3.5.1

dependencies:
  args: ^2.6.0
  http: ^1.2.2
  pubspec_parse: ^1.3.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

executables:
  landscape_analysis: landscape_analysis
